### ISSUE TITLE
Add ACP page to enable deletion of the global chat room

### ISSUE THREAD

**Issue by pitaj** [NodeBB/nodebb-plugin-global-chat#1]

**Comment by LetMeDecay** [comment]
If you are use mongdb, after login database, type this can delete chat room
replace 387 to your chat room uid
`
db.getCollection('objects').remove({_key: /chat:room:387:mids$/})
db.getCollection('objects').remove({_key: /chat:rooms:unread$/, value: "387"});
db.getCollection('objects').remove({_key: "chat:room:387:uids"});
db.getCollection('objects').remove({_key: /chat:rooms$/, value: "387"});
`

> https://community.nodebb.org/topic/11973/data-model-of-chat-purge-history

**Comment by FaizanZahid** [comment]
Good work @pita .. Whats the difference between shoutbox and this plugin?

**Comment by pitaj** [comment]
Shoutbox is mostly it's own thing. This plugin uses the built in chats, so it supports access from anywhere a normal chat room can be accessed.

**Comment by pitaj** [comment]
Note:

If you regret deleting your global chat room, it is recoverable. All you have to do is re-enable this plugin, and it will automatically restore the old chat room.
