### ISSUE TITLE
Installation on NodeBB 1.19.7 fails?

### ISSUE THREAD

**Issue by knzone** [NodeBB/nodebb-plugin-global-chat#10]
Hello,

I tried to install nodebb-plugin-global-chat on my fresh NodeBB 1.19.7 installation over ACP. Installation seems OK (no errors). But i can't find any chat configuration after rebuilding & restarting. I think there should be an menu entry in plugins menu after installation? I'm also not able to create a chat widget (also no entry in select box). Any ideas of what I did miss? Or is this plugin not compatible with 1.19.7? Thanks!

Screenshot of activated plugin: [https://www.directupload.net/file/d/6536/y6ms22mm_png.htm](url)

**Comment by pitaj** [comment]
FYI there's no chat widget provided by this plugin.

It looks like you installed the wrong plugin (chats-global instead of global-chat).

**Comment by knzone** [comment]
Oww! You're right, thank you. Got it installed via npm.

FYI: Your readme says it's installable with npm or ACP - but for me it's only the other plugin showing up on plugin search in admin panel - I didn't noticed and so installed the wrong one.
