### ISSUE TITLE
Ability to allow other users to create global chat channels

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/nodebb-plugin-global-chat#2]
Great work on this plugin. Its awesome.

Basically is it possible as an add-on in this plugin to allow users to start creating their own public global chat topic/group channels so that if other people were interested in the topic /channel/group can join that channel and the person who created that channel would be known as the owner and he can kick or invie people out if he wants too.

And all the currently active channels can be visible on some route let's say ourforum/topic-chatrooms

This can allow users to do real time topic based discussing in and they can create dynamic channels themselves on the fly.

They can join and leave channels on the fly based on the list or they can create their own channel.

Just like how stackverflow chat works. People who like jquery, will be doing a jquery channel room to chat about jquery only and so on.

I got this idea from here https://chatrooms.talkwithstranger.com/topic/18666/different-topic-channels/1

**Comment by pitaj** [comment]
I like the idea, but I think maybe the kind of plugin you're looking for is more "public group chat discovery" than "global chat". While the main feature of this plugin is automatically keeping all users in the global chat, the main feature you're looking for is allowing for users to join a group chat without being explicitly invited.

I think your request is a better fit as a separate plugin.
