### ISSUE TITLE
users hide chat message

### ISSUE THREAD

**Issue by arranka** [NodeBB/nodebb-plugin-global-chat#6]
In the global chat the messages that are written in the chat are not seen because it is covered by the users registered to the forum

![](https://i.imgur.com/GedgtWl.png)

This is the view of the cell phone

![](https://i.imgur.com/cMc0iwn.jpg)

maybe a good idea is to put a group on the left and a user on the right, as is in discord, here is an example

![](https://i.imgur.com/qFWxun4.png)

thank you

**Comment by pitaj** [comment]
The user list should be hidden. What theme and skin are you running?

**Comment by arranka** [comment]
I have a custom, hide users with CSS

**Comment by DroidBV8** [comment]
> The user list should be hidden. What theme and skin are you running?

@pitaj 
How to do this please ?
The problem is just on Full mode. On Smartphone it's OK


> I have a custom, hide users with CSS
@arranka  How to do this please ?
